# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Setup Environment'

- script: npm install
  displayName: 'Install Dependencies'
  
- task: Npm@1
  inputs:
    command: 'custom'
    customCommand: 'npm update --save-dev @types/node'

- script: npx ng test --watch=false
  displayName: 'Tests'

- script: npx ng build --prod
  displayName: 'Build'